#!/usr/bin/env bash
set -euo pipefail

ROOT="${ROOT:-V7-HP-PAPER/v19_reader_aligned_selective_update}"
V17="${V17:-V7-HP-PAPER/v17_fedaction_rag}"
PY="${PY:-/home/iiserver31/anaconda3/envs/supv2/bin/python}"
DEVICE="${DEVICE:-cuda}"
CUDA_DEVICE="${CUDA_VISIBLE_DEVICES:-0}"
export CUDA_VISIBLE_DEVICES="${CUDA_DEVICE}"

STAGE="${ROOT}/stage0b_top5_boundary_crossing"
OUT="${STAGE}/retrieval_confirmation"
SPLIT="${OUT}/hotpotqa_development_disjoint_101_400.jsonl"
POOL="${OUT}/pools/hotpotqa_topic_silo_n300.jsonl"
FROZEN_OUT="${OUT}/frozen_n300"
PC2B_OUT="${OUT}/pc2b_n300"

mkdir -p "${OUT}/pools" "${FROZEN_OUT}" "${PC2B_OUT}"

if [[ ! -s "${SPLIT}" ]]; then
  awk 'NR>100 && NR<=400 {print}' "${V17}/data/hotpotqa/development.jsonl" > "${SPLIT}"
fi

if [[ ! -s "${POOL}" ]]; then
  "${PY}" "${V17}/retrieval/01_generate_federated_pools.py" \
    --dataset hotpotqa \
    --split "${SPLIT}" \
    --split-name development \
    --index "${V17}/retrieval/local_indexes/hotpotqa/topic_silo/client_00.sqlite" \
    --output "${POOL}" \
    --partition topic_silo \
    --local-index-root "${V17}/retrieval/local_indexes/hotpotqa/topic_silo" \
    --centroids "${V17}/partitions/centroids/hotpotqa/topic_silo_m20.npy" \
    --origins "${V17}/partitions/client_query_distribution.csv" \
    --client-budget 3 \
    --local-k 5 \
    --pool-size 10 \
    --local-sparse-candidates 20 \
    --encoder BAAI/bge-base-en-v1.5 \
    --device "${DEVICE}" \
    --max-queries 300
fi

"${PY}" "${STAGE}/rescore_checkpoint.py" \
  --checkpoint "${ROOT}/stage0_full_upload/smoke_hotpotqa_seed20260731/frozen/adapter.pt" \
  --development "${SPLIT}" \
  --pool "${POOL}" \
  --output-dir "${FROZEN_OUT}" \
  --label frozen_n300 \
  --max-queries 300 \
  --device "${DEVICE}"

"${PY}" "${STAGE}/rescore_checkpoint.py" \
  --checkpoint "${STAGE}/pc2b_multi_positive/adapter.pt" \
  --development "${SPLIT}" \
  --pool "${POOL}" \
  --output-dir "${PC2B_OUT}" \
  --label pc2b_n300 \
  --max-queries 300 \
  --device "${DEVICE}"

"${PY}" "${STAGE}/01_pc1_boundary_opportunity_audit.py" \
  --frozen-pool "${FROZEN_OUT}/adapted_pool.jsonl" \
  --pc1-pool "${PC2B_OUT}/adapted_pool.jsonl" \
  --development "${SPLIT}" \
  --output-dir "${PC2B_OUT}/boundary_audit"

BASE_SR="$("${PY}" -c "import json;print(json.load(open('${FROZEN_OUT}/rescore_summary.json'))['support_recall_at_5'])")"
BASE_CS="$("${PY}" -c "import json;print(json.load(open('${FROZEN_OUT}/rescore_summary.json'))['complete_support_at_5'])")"

"${PY}" "${STAGE}/summarize_variant_gate.py" \
  --variant-dir "${PC2B_OUT}" \
  --baseline-support-recall-at5 "${BASE_SR}" \
  --baseline-complete-support-at5 "${BASE_CS}"

cp "${PC2B_OUT}/pc2a_gate_summary.json" "${OUT}/n300_gate_summary.json"
cat > "${OUT}/retrieval_go_no_go.md" <<'EOF'
# Stage 0B N=300 Retrieval Confirmation

This file is generated by `run_stage0b_n300_confirmation.sh`.
Reader evaluation remains disabled unless this retrieval gate passes on the disjoint development subset.
EOF
