#!/usr/bin/env python3
"""Build fully nested answer-safety features for the V7-HP selector.

For each outer fold, training-query features are generated by inner query-level
out-of-fold prediction. Outer-test features are generated by a nuisance model
fit only on the complete outer-training split. The target query and every other
outer-test outcome are therefore unavailable to the feature generator.
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Iterable


def project_root() -> Path:
    configured = os.environ.get("FEDE4RAG_ROOT")
    if configured:
        return Path(configured).expanduser().resolve()
    return Path(__file__).resolve().parents[2]


ROOT = project_root()
V23_DIR = ROOT / "V7-HP-PAPER" / "selector_v2_3"
if str(V23_DIR) not in sys.path:
    sys.path.insert(0, str(V23_DIR))

import v23_common as V23  # noqa: E402


def query_hash(query_id: str, salt: str = "") -> int:
    return int(hashlib.md5((salt + query_id).encode("utf-8")).hexdigest(), 16)


def split_query_ids(query_ids: Iterable[str], k: int = 5, salt: str = "nested-safe") -> list[set[str]]:
    ordered = sorted(set(query_ids), key=lambda q: query_hash(q, salt))
    return [set(ordered[i::k]) for i in range(k)]


def query_fingerprint(query_ids: Iterable[str]) -> str:
    payload = "\n".join(sorted(set(query_ids))).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def fit_nuisance(rows: list[dict[str, Any]]):
    if not rows:
        raise ValueError("Cannot fit answer-safety nuisance model on zero rows")
    return V23.fit_classifier(
        rows,
        target="answer_safe",
        model_type="nested_answer_safe_nuisance",
        drop_support=False,
        drop_safety=True,
    )


def with_safe_probability(row: dict[str, Any], probability: float, source: str) -> dict[str, Any]:
    out = dict(row)
    out["legacy_safe_answer_prob"] = V23.fnum(row, "safe_answer_prob", 0.5)
    out["safe_answer_prob"] = float(probability)
    out["nested_safe_answer_prob"] = float(probability)
    out["safe_answer_prob_source"] = source
    return out


def build_outer_fold_features(
    rows: list[dict[str, Any]],
    outer_train_ids: set[str],
    outer_test_ids: set[str],
    outer_fold_id: int,
    inner_folds: int = 5,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    if outer_train_ids & outer_test_ids:
        raise AssertionError("Outer train/test query IDs overlap")

    train_source = [r for r in rows if r["query_id"] in outer_train_ids]
    test_source = [r for r in rows if r["query_id"] in outer_test_ids]
    inner_test_sets = split_query_ids(outer_train_ids, inner_folds, salt=f"outer-{outer_fold_id}-inner-")
    train_features: list[dict[str, Any]] = []
    inner_records = []

    for inner_fold_id, inner_test_ids in enumerate(inner_test_sets):
        inner_train_ids = outer_train_ids - inner_test_ids
        inner_train_rows = [r for r in train_source if r["query_id"] in inner_train_ids]
        inner_test_rows = [r for r in train_source if r["query_id"] in inner_test_ids]
        nuisance = fit_nuisance(inner_train_rows)
        for row in inner_test_rows:
            train_features.append(
                with_safe_probability(
                    row,
                    nuisance.prob(row),
                    f"outer_{outer_fold_id}_inner_oof_{inner_fold_id}",
                )
            )
        inner_records.append(
            {
                "inner_fold_id": inner_fold_id,
                "n_train_queries": len(inner_train_ids),
                "n_test_queries": len(inner_test_ids),
                "n_train_actions": len(inner_train_rows),
                "n_test_actions": len(inner_test_rows),
                "train_query_fingerprint": query_fingerprint(inner_train_ids),
                "test_query_fingerprint": query_fingerprint(inner_test_ids),
                "query_overlap": len(inner_train_ids & inner_test_ids),
            }
        )

    if {r["query_id"] for r in train_features} != outer_train_ids:
        raise AssertionError("Inner OOF predictions do not cover every outer-training query")
    if len(train_features) != len(train_source):
        raise AssertionError("Inner OOF action count mismatch")

    outer_nuisance = fit_nuisance(train_source)
    test_features = [
        with_safe_probability(row, outer_nuisance.prob(row), f"outer_{outer_fold_id}_train_only")
        for row in test_source
    ]

    audit = {
        "outer_fold_id": outer_fold_id,
        "n_outer_train_queries": len(outer_train_ids),
        "n_outer_test_queries": len(outer_test_ids),
        "n_outer_train_actions": len(train_features),
        "n_outer_test_actions": len(test_features),
        "outer_train_query_fingerprint": query_fingerprint(outer_train_ids),
        "outer_test_query_fingerprint": query_fingerprint(outer_test_ids),
        "outer_query_overlap": len(outer_train_ids & outer_test_ids),
        "inner_folds": inner_records,
        "train_feature_sources": dict(Counter(r["safe_answer_prob_source"] for r in train_features)),
        "test_feature_sources": dict(Counter(r["safe_answer_prob_source"] for r in test_features)),
        "legacy_feature_used": False,
        "outer_test_outcomes_used_for_nuisance_training": False,
        "outer_test_labels_used_for_threshold_or_coverage_tuning": False,
    }
    return train_features, test_features, audit


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def write_jsonl(path: Path, rows: Iterable[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")

